### ISSUE TITLE
How to decode base64 in CPM?

### ISSUE THREAD

**Issue by ianeinser** [dongri/emvco-qrcode#23]
Hello,

great work! I am trying to develop parse function for CPM but i am stucked when trying to decode base64 scanned QR code for e.g. 

hQVDUFYwMWEaTwegAAAAVVVVVw8SNFZ4kBI0WNGRIgESNF8=

what i get is:

�CPV01aO�UUUW4Vx�4Xё"4_

what do i miss?

**Comment by dongri** [comment]
@ianeinser Sorry, CPM decode is not supported yet
