### ISSUE TITLE
How do we actually generate the QR code ?

### ISSUE THREAD

**Issue by nstephane** [dongri/emvco-qrcode#26]
Can I know how the QR code gets generated ? It  isn't very clear please

**Comment by dongri** [comment]
Hi @nstephane 

This library does not generate QR Code as an image, but generates QR Code data.

If you want to generate QR Code, you can use the following libraries.
https://github.com/skip2/go-qrcode

**Comment by nstephane** [comment]
Thank you @dongri for you quick response. :) 
"Stupid question" but how  can I use your project to generate the images with that library? is that possible ?

**Comment by dongri** [comment]
1. create QR Code data
https://github.com/dongri/emv-qrcode/blob/master/README.md
![Screen Shot 2022-07-05 at 21 17 33](https://user-images.githubusercontent.com/878993/177325432-66e02b46-e69f-45d9-89eb-0c279dbb7214.png)

2. QR Code image generation using library
https://github.com/skip2/go-qrcode/blob/master/README.md
![Screen Shot 2022-07-05 at 21 19 17](https://user-images.githubusercontent.com/878993/177325776-502e819b-1269-47ee-9c71-b1a9364ec547.png)

replace "https://example.org" to "0002010102121313JCB1234567....."
