### ISSUE TITLE
使用tag34不能生成微信的二维码

### ISSUE THREAD

**Issue by washingtin** [dongri/emvco-qrcode#3]
Merchant Account Information “3443”

**Comment by washingtin** [comment]
> Merchant Account Information “3443”

把15改成34了

**Comment by dongri** [comment]
微信是34吗？
好的，我想想办法

**Comment by dongri** [comment]
@washingtin 
https://github.com/dongri/emvco-qrcode/pull/4/files
可以自定义tag了

**Comment by washingtin** [comment]
> @washingtin
> https://github.com/dongri/emvco-qrcode/pull/4/files
> 可以自定义tag了

好的，谢谢
