### ISSUE TITLE
 Merchant Account Information may have multiple data

### ISSUE THREAD

**Issue by mitu217** [dongri/emvco-qrcode#5]
According to the [document](https://github.com/dongri/emvco-qrcode-doc/blob/master/EMVCo-Merchant-Presented-QR-Specification-v1-1.pdf) MPM's `Merchant Account Information`  is as follows

```
The format and value are unique and specific to a payment system and several values may be included in the QR Code.
```

Therefore, EMVQR's `MerchantAccountInformation` should be `[] MerchantAccountInformation` or `[]*MerchantAccountInformation`.

**Comment by dongri** [comment]
Thank you!
I change merchant account information type

https://github.com/dongri/emvco-qrcode/commit/bdba9f345bd1b09de51e19d1e5069ff64d4001b3

**Comment by mitu217** [comment]
@dongri 

Thank you for fix 🙏 
Closed because I confirmed the commit
